package managers;

import console.Print;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.sql.*;

public class DatabaseHandler {

    private final String JDBC_DRIVER = "org.postgresql.Driver";
    private String url;
    private String user;
    private String password;
    private Connection connection;
    private Print console;
    static final Logger databaseHandlerLogger = LoggerFactory.getLogger(DatabaseHandler.class);

    public DatabaseHandler(String url, String user, String password, Print console) {
        this.url = url;
        this.user = user;
        this.password = password;
        this.console = console;

        connectToDatabase();
        createTables();
    }

    private void connectToDatabase() {
        try {
            Class.forName(JDBC_DRIVER);
            connection = DriverManager.getConnection(url, user, password);
            console.println("Соединение с базой данных установлено.");
            databaseHandlerLogger.info("Соединение с базой данных установлено.");
        } catch (SQLException exception) {
            console.printError("Произошла ошибка при подключении к базе данных.");
            databaseHandlerLogger.error("Произошла ошибка при подключении к базе данных.");
        } catch (ClassNotFoundException exception) {
            console.printError("Драйвер управления базой данных не найден.");
            databaseHandlerLogger.error("Драйвер управления базой данных не найден.");
        }
    }

    public void closeConnection() {
        if (connection == null) return;
        try {
            connection.close();
            console.println("Соединение с базой данных разорвано.");
            databaseHandlerLogger.info("Соединение с базой данных разорвано.");
        } catch (SQLException exception) {
            console.printError("Произошла ошибка при разрыве соединения с базой данных.");
            databaseHandlerLogger.error("Произошла ошибка при разрыве соединения с базой данных.");
        }
    }

    public PreparedStatement getPreparedStatement(String sqlStatement, boolean generateKeys) throws SQLException {
        PreparedStatement preparedStatement;
        try {
            if (connection == null) throw new SQLException();
            int autoGeneratedKeys = generateKeys ? Statement.RETURN_GENERATED_KEYS : Statement.NO_GENERATED_KEYS;
            preparedStatement = connection.prepareStatement(sqlStatement, autoGeneratedKeys);
            return preparedStatement;
        } catch (SQLException exception) {
            if (connection == null)
                databaseHandlerLogger.error("Соединение с базой данных не установлено!");
            throw new SQLException(exception);
        }
    }

    public void closePreparedStatement(PreparedStatement sqlStatement) throws SQLException {
        if (sqlStatement == null) return;
        try {
            sqlStatement.close();
        } catch (SQLException exception) {
            throw new SQLException(exception);
        }
    }

    public void createTables() {
        try {
            connection.prepareStatement(SQLRequests.CREATE_TABLES).execute();
            databaseHandlerLogger.info("Табоицы успешно созданы.");
        } catch (SQLException exception) {
            console.printError("Произошла ошибка.");
        }
    }
}
